name: Infrastructure CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/deploy-infra.yml
      - 'config.bicepparam'
      - 'main.bicep'
      - 'modules/**'
  push:
    branches: [ main ]
    paths:
      - .github/workflows/deploy-infra.yml
      - 'config.bicepparam'
      - 'main.bicep'
      - 'modules/**'

permissions:
  id-token: write
  contents: read

jobs:
  # JOB 1: Runs ONLY on Pull Requests to validate the Bicep code
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate Bicep Syntax & What-If
        uses: azure/cli@v2
        with:
          inlineScript:
            az deployment sub create \
              --location "centralindia" \
              --parameters ./config.bicepparam

  # JOB 2: Runs ONLY when code is merged/pushed to main
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment sub create \
              --name "mlops-infra-deployment" \
              --location "centralindia" \
              --parameters ./config.bicepparam